Traceback (most recent call last):
  File "main.py", line 231, in <module>
    main(**vars(FLAGS))
  File "main.py", line 196, in main
    model = bp_net(kwargs["depth"], kwargs["in_dim"], kwargs["hid_dim"],
  File "/Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/Models/bp.py", line 41, in __init__
    self.layers = nn.ModuleList(self.init_layers(in_dim, hid_dim, out_dim, params))
  File "/Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/Models/bp.py", line 47, in init_layers
    layers.append(bp_layers(dims[d], dims[d + 1], self.device, params))
  File "/Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/Models/bp.py", line 18, in __init__
    self.forward_function_1 = self.set_function(in_dim, in_dim, params["ff1"])
KeyError: 'ff1'